.\" Process this file with
.\" groff -man -Tascii patchelf.1
.\"
.TH PATCHELF "1" "MARCH 2014" "0.8-1"
.SH NAME
PatchELF - Modify ELF files

.SH SYNOPSIS
.B patchelf \fIOPTION FILE

.SH DESCRIPTION

PatchELF is a simple utility for modifying existing ELF executables
and libraries. It can change the dynamic loader ("ELF interpreter")
of executables and change the RPATH of executables and libraries.

.SH OPTIONS

The single option given operates on a given FILE, editing in place.

.IP "\fB--interpreter \fIINTERPRETER\fR | \fB--set-interpreter \fIINTERPRETER"
Changes the dynamic loader ("ELF interpreter") of an executable given
to INTERPRETER.

.IP "\fB--print-interpreter"
Prints the ELF interpreter of an executable.

.IP "\fB--set-rpath \fIRPATH"
Changes the RPATH of an executable or library to RPATH.

.IP "\fB--shrink-rpath"
Removes all directories from RPATH that do not contain a
library referenced by DT_NEEDED fields of the executable or library.

For instance, if an executable references one library libfoo.so, and
has an RPATH "/lib:/usr/lib:/foo/lib", and libfoo.so can only be found
in /foo/lib, then the new RPATH will be "/foo/lib".

.IP "\fB--print-rpath"
Prints the RPATH of an executable or library.

.IP "\fB--force-rpath"
Forces the use of the obsolete DT_RPATH in the file instead of
DT_RUNPATH. By default DT_RPATH is converted to DT_RUNPATH.

.IP "\fB--add-needed \fILIBRARY"
Adds a declared dependency on a dynamic library. This option can
be given multiple times.

.IP "\fB--remove-needed \fILIBRARY"
Removes a declared dependency on a dynamic library. This option can
be given multiple times.

.IP "\fB--add-list \fR|\fB --add-needed-list \fILIBRARY1\fR,\fILIBRARY2\fR,..."
The same as '--add-needed', but with several dynamic library declared
at once through a comma seperated list.

Note that a trailing comma will create an empty NEEDED entry, which
can be removed with the following command:
 patchelf --remove-needed ""

.IP "\fB--remove-list \fR|\fB --remove-needed-list \fILIBRARY1\fR,\fILIBRARY2\fR,..."
The same as '--add-needed-list', but it removes the libraries.
Trailing commas will be ignored.

.IP "\fB--replace-needed \fILIBRARY NEW_LIBRARY"
Replaces a declared dependency on a dynamic library. This option can
be given multiple times.

.IP "\fB--debug"
Prints details of the changes made to the input file.

.IP "\fB\-h \fR|\fB \--help"
Prints help information.

.IP "\fB\-V \fR|\fB \--version"
Shows the version of patchelf.

.SH AUTHORS
.I http://nixos.org/patchelf.html
.PP
2004-2014, Eelco Dolstra <\fIeelco.dolstra@logicblox.com\fR>
.br
     2011, Zack Weinberg
.br
     2011, Jeremy Sanders <\fIjeremy@jeremysanders.net\fR>
.br
     2012, vdanjean
.br
     2013, rgcjonas
.br
     2014, djcj <\fIdjcj@gmx.de\fR>
.PP
This manpage was written by Jeremy Sanders <\fIjeremy@jeremysanders.net\fR>
and modified by Eelco Dolstra <\fIeelco.dolstra@logicblox.com\fR>
and djcj <\fIdjcj@gmx.de\fR>.

.SH "SEE ALSO"
.BR elf (5),
.BR ld.so (8)
